### ISSUE TITLE
kcli console ouputs error for remote-viwer on kvm

### ISSUE THREAD

**Issue by flloreda** [karmab/kcli#132]
kcli console ouputs error for remote-viwer on kvm, it seems a simple typo

**Comment by flloreda** [comment]
Pull request sent https://github.com/karmab/kcli/pull/133

**Comment by karmab** [comment]
your PR along with this last commit https://github.com/karmab/kcli/commit/8f41f242a6bc7d6e2eff7b5843a54f02e654f3f8
will handle correctly 
- getting console for both tunneled and not tunneled connections
- forcing tunnel mode for vm where graphical tcp listen is set to 127.0.0.1 in the vm xml
- cleaner debug so that the full command is displayed with `kcli --debug console`   (similarly to what we do for kcli ssh)
