### ISSUE TITLE
klist not in rpm

### ISSUE THREAD

**Issue by cherusk** [karmab/kcli#177]
You're claiming klist is coming installed via rpm:

> doc/index.md:It's also present at `/usr/share/doc/kcli/extras/klist.py` in the rpm and `/usr/bin/klist.py` in the container

Cannot confirm that.

**Comment by cherusk** [comment]
+ /usr/share/doc/kcli/extras/klist.py --help

sh: line 4: /usr/share/doc/kcli/extras/klist.py: No such file or directory

**Comment by cherusk** [comment]
Yet it's in the container as specified at `/usr/bin/klist.py`

**Comment by karmab** [comment]
i ve run the following command and it seems to be there

```
rpm -ql kcli | grep extra
/usr/lib/python3.6/site-packages/kvirt/static/vnc/app/images/toggleextrakeys.svg
/usr/share/doc/kcli/extras
/usr/share/doc/kcli/extras/alpine
/usr/share/doc/kcli/extras/genrst.sh
/usr/share/doc/kcli/extras/i_am_a_container
/usr/share/doc/kcli/extras/k8sdeploy.yml
/usr/share/doc/kcli/extras/klist.py
```

**Comment by cherusk** [comment]
Odd. But look here: https://travis-ci.com/cherusk/godon/builds/148990700

At the bottom of it, you can also see what I install, it's the latest rpm.

Maybe some rpm placement hook is not run?

**Comment by karmab** [comment]
i think your build is not using a rpm (the image beeing an ubuntu one) but docker.
using the klist.py dynamic inventory from container is a bit more tricky, you' ll need to create an helper script as stated in https://kcli.readthedocs.io/en/master/#ansible-support
regarding using a deb instead of docker, let me fix it in my CI, for some reason the automatic generation of deb from travis was not working (as it does for rpm), i will solve it so you can alternatively use that (and make sure you get latest build)

**Comment by cherusk** [comment]
Hold on, I'm using the latest rpm in the docker image, the container image is fedora (30) based.

Only the host level is deb based, but that's isolated away.
