### ISSUE TITLE
zsh: complete: command not found...

### ISSUE THREAD

**Issue by vashirov** [karmab/kcli#185]
`kcli` installation modifies `.zshrc`.
After I open terminal with a new shell, I have this error message:
```
zsh: complete: command not found...
```
I had to add the following 2 lines before `eval` to fix this:
```
autoload bashcompinit
bashcompinit
```

**Comment by karmab** [comment]
sorry for the intrusive editing of your shell....
i've fixed it in this commit https://github.com/karmab/kcli/commit/d82b499e398fc8133eed2b8a17b4befffc18d570
by actually removing the code that adds the completion and instead points to the corresponding documentation item, so that users can do it manually should they decide to do so.
