### ISSUE TITLE
Slow performance towards vSphere/VMWare when using `kcli list ...` related cmds

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#299]
Hi @karmab,

We've already chatted about this on Slack. Now, I just wanted to create an issue about. To make it more official and to at some point hopefully get it fixed. If possible.

# SEEING

Slow performance when listing vm's, disks and so forth with `kcli list ...` related cmds. We're talking about up to and + 1min at times.

I have access to a quite big VMWare environment and can therefore help you troubleshoot this as well as try out different approaches.

# LOOKING FOR

That `kcli list ...` related cmds are reasonably fast. I would say 5-10 secs.

**Comment by karmab** [comment]
the only thing i can think of is optimizing a bit the code cos i think the vsphere api is naturally slow, so we need to try retrieving objects when listing in a smarter way

**Comment by LarsBingBong** [comment]
Naturally slow ;-) ... you're so kind. Should one post an issue somewhere at VMWare? But, all the optimization that can be done would be wonderful.

**Comment by karmab** [comment]
changed a bit the listinfo code in https://github.com/karmab/kcli/commit/3af7f5ae5737c369ca8c4ec6ba52db1136d41578
hopefully it speeds things a bit

**Comment by LarsBingBong** [comment]
Hi @karmab,

I think it's better but still quite slow. Consistently at 15sec per list request. That makes it somewhat of a slacking experience to work with KCLI for general management tasks.

If there's more seconds to get sliced of the wait time it would be great. I think, anything above 5sec is too slow. What do you think?

**Comment by karmab** [comment]
opened https://github.com/vmware/pyvmomi/issues/980 to track slowness

**Comment by prziborowski** [comment]
Just wanted to comment here as this was linked to the pyvmomi entry.
Each time you make a "vm.<something" statement, it is making a request to the server to fetch that <something>.

So for example:
```
        yamlinfo['cpus'] = vm.config.hardware.numCPU
        yamlinfo['memory'] = vm.config.hardware.memoryMB
        yamlinfo['status'] = translation[vm.runtime.powerState]
        yamlinfo['nets'] = []
        yamlinfo['disks'] = []
        if vm.runtime.powerState == "poweredOn":
            yamlinfo['host'] = vm.runtime.host.name
            for nic in vm.guest.net:
                if 'ip' not in yamlinfo and nic.ipAddress:
                    yamlinfo['ip'] = nic.ipAddress[0]
        for entry in vm.config.extraConfig:
```
This will make 6 requests (vm.config 3 times, vm.runtime 2 times, vm.guest) for VM properties, and depending on the distance between client and server, it could take some time.

This is also why the `find` function will be much slower than the `findvm` function because find is fetching the 'name' property in a loop as individual requests and findvm is getting the name property when it collects the VM object references.

You could use the property collector's RetrievePropertiesEx to fetch config, runtime, guest in 1 call.
Similarly for list, you could collect additional properties than name to reduce roundtrips:
```
        vmlist = collectproperties(si, view=view, objtype=vim.VirtualMachine, pathset=['name'], includemors=True)
        for o in vmlist:
            vm = o['obj']
            if vm.summary.runtime.connectionState != 'orphaned' and not vm.config.template:
                if self.filtervms and 'plan' not in [x.key for x in vm.config.extraConfig]:
                    continue
                vms.append(self.info(o['name'], vm=vm))

```
2 vm.config calls and 1 vm.summary call, for each vm in the list. And then goes into the info function, which does 6 more requests.

**Comment by larssb** [comment]
Thank you for chiming in Mr. @prziborowski - much appreciated. This looks really interesting. Good insights into what's going on behind the scenes.

**Comment by karmab** [comment]
ongoing PR at https://github.com/karmab/kcli/pull/408 based on @prziborowski recommended approach

**Comment by larssb** [comment]
Thank you @karmab and @prziborowski - with https://github.com/karmab/kcli/commit/f56ff90bbece924dd57d4a401742f79145d43359 and https://github.com/karmab/kcli/commit/95e2592d67545ebd4263c73f121c6c143fb41adf we can close this issue.

It's waaaay faster now. Really an improvement. Much wanted and much needed.

Thank you!
