### ISSUE TITLE
Fix that one need to add join.sh to the `cmds` sections of a `VMRules` section. When deploying K3s

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#300]
# THE ISSUE IN DETAILS

When I deploy K3s and I want to customize the deployed nodes. I do that via a `cmds` section in the `vmrules` section of a **KCLI** plans file. However, doing that clashes with the setup of K3s worker nodes. As the join.sh file is then not being run when a `cmds` section is defined.

# THE WORKAROUND

Simply to just add `- bash /root/join.sh` as the last line or whatever in the `cmds` section for each node being customized via `vmrules`.

# EXPECTED BEHAVIOUR

That I'm able to use `cmds` sections when customizing K3s nodes via `vmrules` and the **join.sh** file is still being run.

# SUGGESTION

As we've already talked over on Slack @karmab - the idea is to simply merge the content of the pre-configured `cmds` section in the K3s `workers.yml` file.

**Comment by karmab** [comment]
probably what we want to do is that for a subset of keywords (cmds, scripts and files), vmrules does a merge

**Comment by LarsBingBong** [comment]
For sure! If this is an issue for several keywords I strongly agree. The user experience should be the same for all keywords.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/514e12281f6c1c3008edda03d5b2f1e68a09840b
so that the behaviour is to extend the profile entry with the content of vmrules for cmds, scripts and files.
For other keywords, in particular, disks and nets, we still do a full replacement, otherwise an user couldnt use vmrules to tweak a specific entry (for instance, the mac address in the first nic of a vm when this attribute isnt exposed in a plan)
