### ISSUE TITLE
Support `Distributed Resource Scheduler` rules or `VMware Affinity rules`

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#301]
# SCENARIO

If one wants to assign certain VM's to specific VMWare hosts one can do so with either DRS rules or VMWare Affinity Rules. I would KCLI to support one of these.

Fine, it it's the `VMWare Affinity rules` as we've already talked about those and there's an example in the wild on how to do that with `pyVmomi`. So let's go with that.
My VMWare expert colleague also does a head nod towards the `VMWare Affinity rules` to be fine.

## Specific use-case

I want to assign K3s worker nodes (e.g. the VM's). Only a select few in a K3s cluster to certain VMWare hosts - because these VMWare hosts have been optimized for MSSQL workloads as well as the Microsoft MSSQL enterprise rules.

---

Here's the example you've found > https://encoretechnologies.github.io/blog/2019/01/vmware-affinity-rules/

Thank you @karmab

**Comment by LarsBingBong** [comment]
Any news on this?

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/pull/321
the requisite is to create the hostgroup by yourself (using UI for instance) so that you can associate your hosts to it.
Then, when creating a vm, one can provide 3 extra parameters:
- vmgroup: if it doesnt exist, the group will be created and in any case, the vm will get added to it.
- hostgroup and hostrule: if both are provided and the hostrule doesnt exist, it will be created as affinity rule with the vmgroup and the hostgroup to it.

Note that when using this within a plan (or a cluster), it's enough to provide hostgroup and hostrule for the first vm of the plan so that the hostrule gets created ( though a kcli vmrule for instance), and vmgroup for all of them, so that the group gets created with the first vm, and then the remaining vm only get added.

Finally, note that so far, vmgroups and hostrules dont get deleted along with vms (to ease recreation of the same assets), but it might change in the future (for consistency purposes)
