### ISSUE TITLE
Non-actionable error message "No usable public key found, which is required for the deployment" 

### ISSUE THREAD

**Issue by rwmjones** [karmab/kcli#456]
```
# kcli create kube generic -P masters=3 -P workers=3 -P network=kubenet -P version=1.24  -P  api_ip=192.168.24.254 kube124
No usable public key found, which is required for the deployment
```

All error messages should be actionable.  They should tell the user what action needs to be taken to resolve the issue.

In this case I had to ask around and it turns out that the root account doesn't have an SSH key which is something I would never have worked out from the error message.

**Comment by rwmjones** [comment]
Here are a couple more:
```
Image centos8stream not Added because Pool None not found
kube124-master-0 not deployed because Pool default not found
```

Because I know about libvirt I'm going to guess that "Pool" refers to something to do with libvirt pools, but if I didn't happen to be a libvirt developer I would never know that.  Again, error messages must describe what actions need to be taken to resolve the issue.

**Comment by karmab** [comment]
well, that s a good debate. I agree with you but:

- about the first message "No usable public key found", either a default pub key for the current user is automatically detected (from ~/.ssh), or a one defined in ~/.kcli or a one provided through the keys array so there are several ways to have a public key available for consumption here, and i wouldnt expect the error message to detail all of this. Doc should definitely expand more on this topic though
- about the second message, actually pool refers to storage unit, which is a libvirt pool with libvirt, but something different on other platforms (datastore in vsphere o storage domain in rhv for instance) but you're right that for a user not so familiar with libvirt, what action to take in this case is gonna be tricky. Hopefully it doesnt happen that much because:
   - in general, default pool is already there
   - If it's not, the doc section at https://kcli.readthedocs.io/en/latest/#configuration covers how to create it (using kcli)

**Comment by rwmjones** [comment]
The error message should say the above, either literally or by pointing to the relevant place in the documentation.

**Comment by karmab** [comment]
enhanced the message about public key with https://github.com/karmab/kcli/commit/2b11e9d3f68538a7bec446808fac69b5df01325f

**Comment by karmab** [comment]
handling the pool message in the related issue
