### ISSUE TITLE
Integration w/ KubeVirt

### ISSUE THREAD

**Issue by NerdsvilleCEO** [karmab/kcli#90]
How easy would it be to integrate KCli w/ KubeVirt for managing libvirt configuration? It seems like there is a bit of duplication of work between the two projects

https://github.com/kubevirt/kubevirt

**Comment by karmab** [comment]
hello, as im actually somehow involved in the kubevirt project, i have been adding it as a kubevirt plugin.
it's already functional, just hitting some issues around pvc based templates ( instead of registry disks)
but it s ready for testing and to be included in this week's release, along with a proper documentation.

if deploying from git, you can use it by creating an additional section like the following one in ~/.kcli
(optional context and usecloning keys can be specified )

```
kubevirt:
 type: kubevirt
 enabled: true
```

**Comment by NerdsvilleCEO** [comment]
Cool! Btw I made a shout out about KCLI at the Southern California Linux Expo :) they were talking about KubeVirt and I brought up your tool, it simplifies so much! Closing this issue

**Comment by karmab** [comment]
to be complete, note that authentication is handled outside the tool, that is, you need a proper ~/.kube/config with the info to connect to your cluster to use kubevirt in kcli.
( if you have several contexts, you can poin to one in the config although i prefer to let the variable undefined so that current context is always used)
